In [2]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt 
import urllib.request, json

2023-11-23 14:28:18.575768: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-23 14:28:18.608131: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-23 14:28:18.608172: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-23 14:28:18.608190: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-23 14:28:18.613519: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-23 14:28:18.613989: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-23 14:28:19.295817: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [3]:
np.random.seed(20)
tf.random.set_seed(20)

In [4]:
from datetime import date
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from keras.models import Sequential, Model
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate

In [5]:
df = pd.read_csv('Gasoline.csv')
#df = pd.read_csv('Diesel.csv')
df

         Tanggal    qty       Jumlah
0     2016-01-01   8694   63467076.0
1     2016-01-02  10044   73320032.0
2     2016-01-03  13928  101671188.0
3     2016-01-04  12518   91382972.0
4     2016-01-05  11112   77424375.0
...          ...    ...          ...
1993  2021-10-25  12239   93628350.0
1994  2021-10-26  11319   86590350.0
1995  2021-10-27  12502   95640300.0
1996  2021-10-28  12456   95288400.0
1997  2021-10-29  11228   85894200.0

[1998 rows x 3 columns]

In [6]:
stockprices = df.sort_values('Tanggal')

In [7]:
def calculate_rmse(y_actual, y_predict):
    rmse = np.sqrt(np.mean((y_actual - y_predict)**2))
    return rmse
def calculate_mape(y_actual, y_predict):
    y_predict, y_actual = np.array(y_predict), np.array(y_actual)
    mape = np.mean(np.abs((y_actual - y_predict) / y_actual)) * 100
    return mape
def extract_seqX_outcomeY(data, N, offset_value):
    training_Sequence_X = []
    output_value_y = []

    for i in range(offset_value, len(data)):
        training_Sequence_X.append(data[i-N:i])
        output_value_y.append(data[i])

    return np.array(training_Sequence_X), np.array(output_value_y)

In [8]:
training_ratio = 0.8
test_ratio = 0.2

training_size = int(training_ratio * len(stockprices))
testing_size = int(test_ratio * len(stockprices))

print('training_size: ' + str(training_size))
print('testing_size: ' + str(testing_size))

train = stockprices[:1670][['Tanggal', 'Jumlah']]
test = stockprices[1670:][['Tanggal', 'Jumlah']]

print(train.shape)
print(test.shape)

training_size: 1598
testing_size: 399
(1670, 2)
(328, 2)

In [9]:
stockprices = stockprices.set_index('Tanggal')
stockprices

              qty       Jumlah
Tanggal
2016-01-01   8694   63467076.0
2016-01-02  10044   73320032.0
2016-01-03  13928  101671188.0
2016-01-04  12518   91382972.0
2016-01-05  11112   77424375.0
...           ...          ...
2021-10-25  12239   93628350.0
2021-10-26  11319   86590350.0
2021-10-27  12502   95640300.0
2021-10-28  12456   95288400.0
2021-10-29  11228   85894200.0

[1998 rows x 2 columns]

In [10]:
window_size=60

In [11]:
import time
mulai = time.time()

layer_units = 128
optimizer = 'adam'
current_epochs = 5
current_batch_size = 2

current_LSTM_parameters = {'units': layer_units,
                           'batch_size': current_batch_size,
                           'optimizer' : optimizer,
                           'epochs': current_epochs
                          }
    
## use the past N stock prices for training to predict the N+1th closing price

# scale 
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(stockprices[['Jumlah']])
scaled_data_train = scaled_data[:train.shape[0]]
   
X_train, y_train = extract_seqX_outcomeY(scaled_data_train, window_size, window_size)

### build a LSTM model
def Run_LSTM(X_train, layer_units = 64):
    inp = Input(shape=(X_train.shape[1], 1))

    x = LSTM(units=layer_units, return_sequences=True)(inp)
    x = LSTM(units=layer_units)(x)
    model.add(Dropout(0.2))
    out = Dense(1, activation='linear')(x)
    model = Model(inp, out)

    # Compile the LSTM model
    model.compile(loss = 'mean_squared_error')

    return model
    
model = Run_LSTM(X_train, layer_units = layer_units)

history = model.fit(X_train, y_train, epochs=current_epochs, batch_size=current_batch_size, verbose=1, validation_split=0.1, shuffle=True)

# predicting stock price using past window_size stock prices
def preprocess_test_data(data=stockprices, scaler=scaler, window_size=window_size, test=test): 
    raw = data['Jumlah'][len(data) - len(test) - window_size:].values
    raw = raw.reshape(-1,1)
    raw = scaler.transform(raw)

    X_test = []
    for i in range(window_size, raw.shape[0]):
        X_test.append(raw[i-window_size:i, 0])
        
    X_test = np.array(X_test)

    X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
    return X_test
    
X_test = preprocess_test_data()

predicted_price_ = model.predict(X_test)
predicted_price = scaler.inverse_transform(predicted_price_)

# plot predicted price vs actual closing price
test['Predictions_lstm'] = predicted_price

# Evaluate performance
rmse_lstm = calculate_rmse(np.array(test['Jumlah']), np.array(test['Predictions_lstm']))
mape_lstm = calculate_mape(np.array(test['Jumlah']), np.array(test['Predictions_lstm']))


### Plot preidiction and true trends
def plotting_stock_trend_lstm(train, test):        
    fig = plt.figure(figsize = (16,8))
    plt.plot(train['Tanggal'], train['Jumlah'], label = 'Train Closing Price')
    plt.plot(test['Tanggal'], test['Jumlah'], label = 'Test Closing Price')
    plt.plot(test['Tanggal'], test['Predictions_lstm'], label = 'Predictions')
    plt.title('LSTM Model')
    plt.xlabel('Tanggal')
    plt.ylabel('Stock Price')
    plt.legend(loc="upper left")

plotting_stock_trend_lstm(train, test,)

akhir = time.time()
waktu_detik = akhir - mulai
waktu_menit = "{:.2f}".format(waktu_detik / 60)

print("RMSE  :",rmse_lstm)
print("MAPE %:",mape_lstm)


print(f"Program run in = {waktu_menit} min")

UnboundLocalError: local variable 'model' referenced before assignment